### ISSUE TITLE
[Bug] Cant see all teams as organization owner

### ISSUE THREAD

**Issue by pschmidt88** [katalon-studio/katalon-testops#101] opened 2020-01-20 14:44 UTC
I'm the owner of our organization, but I can only see the teams I'm a member of.

The (organization) owner role was transferred to me, because my co-worker left the company. Before that he was in charge und I think he created all other teams and projects.

Is this a bug or intended behavior?

**Comment by Padoplin** [comment] 2020-01-21 02:56
Hello Paul,

It is intended behavior. Transferring Organization ownership does NOT affect Team ownership. The previous Owner still has full permission as a Team Owner to those teams having been created by them before. In your case, I recommend you to ask the Team Admins to invite you to each team and grant you an Admin role if needed.

For more information about transferring ownership, please see [here](https://docs.katalon.com/katalon-analytics/docs/user-management.html#transfer-organization-ownership-to-the-existing-team-member).

Padoplin

**Closed** 2020-07-20 06:37 UTC
